<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Migrations\AbortMigrationException;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20200907090820 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws AbortMigrationException
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE vendor_onetomanyunidirectional_domain_model_post (persistence_object_identifier VARCHAR(40) NOT NULL, created DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vendor_onetomanyunidirectional_domain_model_blog (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vendor_onetomanyunidirectional_domain_model_blog_posts_join (onetomanyunidirectional_blog VARCHAR(40) NOT NULL, onetomanyunidirectional_post VARCHAR(40) NOT NULL, INDEX IDX_B824F894F1E40E20 (onetomanyunidirectional_blog), UNIQUE INDEX UNIQ_B824F8946B7B33EE (onetomanyunidirectional_post), PRIMARY KEY(onetomanyunidirectional_blog, onetomanyunidirectional_post)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE vendor_onetomanyunidirectional_domain_model_blog_posts_join ADD CONSTRAINT FK_B824F894F1E40E20 FOREIGN KEY (onetomanyunidirectional_blog) REFERENCES vendor_onetomanyunidirectional_domain_model_blog (persistence_object_identifier) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vendor_onetomanyunidirectional_domain_model_blog_posts_join ADD CONSTRAINT FK_B824F8946B7B33EE FOREIGN KEY (onetomanyunidirectional_post) REFERENCES vendor_onetomanyunidirectional_domain_model_post (persistence_object_identifier) ON DELETE CASCADE');
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws AbortMigrationException
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE vendor_onetomanyunidirectional_domain_model_blog_posts_join DROP FOREIGN KEY FK_B824F894F1E40E20');
        $this->addSql('ALTER TABLE vendor_onetomanyunidirectional_domain_model_blog_posts_join DROP FOREIGN KEY FK_B824F8946B7B33EE');
        $this->addSql('DROP TABLE vendor_onetomanyunidirectional_domain_model_blog');
        $this->addSql('DROP TABLE vendor_onetomanyunidirectional_domain_model_blog_posts_join');
        $this->addSql('DROP TABLE vendor_onetomanyunidirectional_domain_model_post');
    }
}